master:
  image: nicor88/docker-spark:latest
  command: /usr/local/spark/bin/spark-class org.apache.spark.deploy.master.Master -h master
  hostname: master
  environment:
    SPARK_CONF_DIR: /conf
    MASTER: spark://master:7077
    PYSPARK_PYTHON: /opt/miniconda/bin/python3.5
  expose:
    - 7001
    - 7002
    - 7003
    - 7004
    - 7005
    - 7006
    - 7077
    - 6066
    - 8888
  ports:
    - 4040:4040
    - 6066:6066
    - 7077:7077
    - 8080:8080
    - 8888:8888
  volumes:
    - ./conf/master:/conf
    - ./data:/data
    - ./notebooks:/notebooks

worker1:
  image: nicor88/docker-spark:latest
  command: /usr/local/spark/bin/spark-class org.apache.spark.deploy.worker.Worker spark://master:7077
  hostname: worker1
  environment:
    SPARK_CONF_DIR: /conf
    PYSPARK_PYTHON: /opt/miniconda/bin/python3.5
    SPARK_WORKER_CORES: 2
    SPARK_WORKER_MEMORY: 1g
    SPARK_WORKER_PORT: 8881
  links:
    - master
  expose:
    - 7012
    - 7013
    - 7014
    - 7015
    - 7016
    - 8881
  volumes:
    - ./conf/worker:/conf
    - ./data:/data

worker2:
  image: nicor88/docker-spark:latest
  command: /usr/local/spark/bin/spark-class org.apache.spark.deploy.worker.Worker spark://master:7077
  hostname: worker2
  environment:
    SPARK_CONF_DIR: /conf
    PYSPARK_PYTHON: /opt/miniconda/bin/python3.5
    SPARK_WORKER_CORES: 2
    SPARK_WORKER_MEMORY: 1g
    SPARK_WORKER_PORT: 8881
  links:
    - master
  expose:
    - 7012
    - 7013
    - 7014
    - 7015
    - 7016
    - 8881
  volumes:
    - ./conf/worker:/conf
    - ./data:/data
